name: Deploy Azure Function

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Step 3: Build project
      - name: Build
        run: dotnet build --configuration Release

      # Step 4: Publish project
      - name: Publish
        run: dotnet publish -c Release -o publish

      # Step 5: Deploy to Azure Function App
      - name: Deployment 
        uses: Azure/functions-action@v1
        with:
          app-name: kusumafuncapp
          package: ./publish
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP }}
